version: "3.9"
services:
  higress:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:latest
    container_name: higress-ai
    restart: always
    ports:
      - "8001:8001"
      - "8080:80"
      - "8443:8443"
    volumes:
      - ./data:/data
    depends_on:
      - redis
      - qdrant

  redis:
    image: redis:latest
    container_name: higress-redis
    restart: always
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: higress-qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
