apiVersion: v1
data:
  data: '{"name":"mulit-aiagent-route","domains":[],"pathPredicate":{"matchType":"PRE","matchValue":"/muilt","caseSensitive":false},"headerPredicates":[],"urlParamPredicates":[],"upstreams":[{"provider":"minimax","weight":50,"modelMapping":{}},{"provider":"aliyun","weight":50,"modelMapping":{}}],"modelPredicates":[],"authConfig":{"enabled":false,"allowedConsumers":[]},"fallbackConfig":{"enabled":false}}'
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    higress.io/config-map-type: ai-route
    higress.io/resource-definer: higress
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
      f:metadata:
        f:labels:
          .: {}
          f:higress.io/config-map-type: {}
          f:higress.io/resource-definer: {}
    manager: Kubernetes Java Client
    operation: Update
    time: "2026-02-12T15:35:31Z"
  name: ai-route-mulit-aiagent-route
  namespace: higress-system
  resourceVersion: "2"
