apiVersion: v1
data:
  data: '{"name":"masgod","domains":[],"pathPredicate":{"matchType":"PRE","matchValue":"/masgod","caseSensitive":false},"headerPredicates":[],"urlParamPredicates":[],"upstreams":[{"provider":"minmax","weight":100,"modelMapping":{}}],"modelPredicates":[],"authConfig":{"enabled":false,"allowedConsumers":[]},"fallbackConfig":{"enabled":false}}'
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-13T07:14:40Z"
  labels:
    higress.io/config-map-type: ai-route
    higress.io/resource-definer: higress
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
      f:metadata:
        f:labels:
          .: {}
          f:higress.io/config-map-type: {}
          f:higress.io/resource-definer: {}
    manager: Kubernetes Java Client
    operation: Update
    time: "2026-02-13T07:14:40Z"
  name: ai-route-masgod
  namespace: higress-system
  resourceVersion: "1"
