apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIF+zCCA+OgAwIBAgIUXBE0gnN/tS/zHLwt2mQ2QeF30Q8wDQYJKoZIhvcNAQEL
    BQAwgYsxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwI
    U2hhbmdoYWkxEDAOBgNVBAoMB0hpZ3Jlc3MxEDAOBgNVBAsMB0dhdGV3YXkxEDAO
    BgNVBAMMB1Jvb3QgQ0ExIDAeBgkqhkiG9w0BCQEWEXJvb3RjYUBoaWdyZXNzLmlv
    MCAXDTI2MDIxMzA4NDQ1MVoYDzIxMjYwMTIwMDg0NDUxWjCBizELMAkGA1UEBhMC
    Q04xETAPBgNVBAgMCFNoYW5naGFpMREwDwYDVQQHDAhTaGFuZ2hhaTEQMA4GA1UE
    CgwHSGlncmVzczEQMA4GA1UECwwHR2F0ZXdheTEQMA4GA1UEAwwHUm9vdCBDQTEg
    MB4GCSqGSIb3DQEJARYRcm9vdGNhQGhpZ3Jlc3MuaW8wggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCPkOYCfESJzsQ9CJ/vPmlhcMzzgn+6X/hmv8cXbLln
    XThPSC0wPmt21aEkkCgminWEtYrMoI7mg8DvMByS68srE9/SYtnvo9lM0X/UpkmW
    j2qAn3IDrncLavD3C+Ms9pS9vb4LFirqWYQoDMcexBmZ8dzSf/+7AaaJViXPPFRE
    No7vbNEWGH63jdSEhUtiVTZWGQ7HE9R3Mkjr0DEddm8e2zbhZyc7ximubRVofpnp
    BJ1V4y2FVYBbR/WrQN0DD93IjgT5Zn9jJz2Bsjf//ueWmQm9QDgH3sXw6/eyBVHC
    Caepg4yudySq0zFnHIFjLj7Szhef5MUOMocFejpM0+HTeisQTDT/FDfKcIQyxgSB
    Z29LhLzBWhrf+i5In2S0ToqWJQ+LNspD0EAnr9P3nQb17hwQsrnI1Vl8W0YulGW2
    8aLpWYfGxQ9Y3UjqNje0vqDT8s6oFMHH75cVLDAuAnuNvsGsFqJ27xml4PpE/4Lz
    K3k2YFLrIvFtxryUTXtRslurZbP37aIwgr9il92TCv5iLUjq5OdjBvtjQirwW7No
    oVueOGTeQzyzbs/pp9wbW3/iQa05VvbOBsE1hcw1s8dp8vh5+4UTgLXQRR+ApyW8
    oMT+508+MJ0vi280ns4cMX1T+QJAwmRhrQH1+b5BGmZwpjw8UbqL49/jSezx1th8
    twIDAQABo1MwUTAdBgNVHQ4EFgQUYT0Jeqcf+yql7HQdsGZIAmxKi0MwHwYDVR0j
    BBgwFoAUYT0Jeqcf+yql7HQdsGZIAmxKi0MwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEAFoWhI7uJvXiUpRtl4KXfuBz/Gs0e8XDQ8s8dybRheMV9
    yA3AoxPRCpgWFW9/MzGgN66A4LYnJwTjj4po8zBv4/K/vrus1CjUsseFAgwRGGSY
    mfFpPpPGLTdx7/67CFeIP2WXj4Hgq+bDxaqLJ3o0O2dk+pTBwTR7ulXe0jx8nQbC
    2ldEvD0LtXNgaoppV+MGdm2v3DRdU7FGSGRJSFwYspX3MngEI9zEKpLkLhKY+4V8
    hEjaDyxwMQxEvTlvHtYFq2j0svkAPzWb/v2yVLefor6cva2QN2I86cFcQWyTqGVX
    EBzK2PkA05Pj9AzPinGAPI6kZJwa6A/r433s3glZdQXMYYy4B2zwoe3nKFBEhI1l
    4ElXkF9y29EQcrY6uJO1xGAA+1yJA9ckfBrLz/R7bTGt7B1sRX4QNtsot0cTIuTg
    vZWc+bKFP+JoI+AXXgTqDUEtO7w+D5FkzuWivAbqbNuoQnIoHx9/P11+svg4KlEA
    sWFwzd4qg/cPtZkznmwW4n9sejEENqBwNwsSDKIrWe6xp3oavApWWKmMyadQLSYu
    G3+n+8CCqtUzoBVveRwPFpj9+8IeNWs7V4PW6HnBPAKvxSeDPztZ/fEtM9/161kg
    Rlo+d3hC+q/mt6cvl/96p6UmyVYvRofFKlm6G3o1mgdJoYUTis22ymnlcsICrCk=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-11T06:32:09Z"
  labels:
    istio.io/config: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:root-cert.pem: {}
      f:metadata:
        f:labels:
          .: {}
          f:istio.io/config: {}
    manager: pilot-discovery
    operation: Update
    time: "2026-02-13T08:44:54Z"
  name: higress-ca-root-cert
  namespace: higress-system
  resourceVersion: "52"
