apiVersion: v1
data:
  cert: |
    acmeIssuer:
    - ak: ""
      email: your30294@yours27529.com
      name: letsencrypt
      sk: ""
    automaticHttps: true
    credentialConfig: []
    fallbackForInvalidSecret: false
    renewBeforeDays: 30
    version: "20260211063155"
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-11T06:31:55Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:cert: {}
    manager: higress
    operation: Update
    time: "2026-02-11T06:31:55Z"
  name: higress-https
  namespace: higress-system
  resourceVersion: "1"
